---
title: "Action Potential - Individual Traces"
output: 
  html_document: default
  pdf_document:
    latex_engine: xelatex
    pandoc_args: --listings
date: "`r Sys.Date()`"
params:
  run: FALSE
  cores: 1
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(doParallel)
library(foreach)
library(knitr)
source("ActionPotential.R")
source("vars.R")

loc_dir = paste("/Trace/", Sys.Date(), "/", sep="")
#loc_dir = paste("/Trace/", "2023-06-01", "/", sep="")
output_folder_trc = paste(output_folder, loc_dir, sep="")
dir.create(output_folder_trc)
```

```{r header, echo=FALSE}
trace_files = c("Atratus_WT.csv", "Atratus_P.csv", 
                "Atratus_EPN.csv")
#trace_files = c("Atratus_WT.csv")
#trace_files = c("Atratus_P.csv")
#trace_files = c("Atratus_EPN.csv")

num_traces = 1
for (file in trace_files) {
  data = read.csv(paste(data_folder, file, sep=""), skip=3)
  num_traces_cur = (ncol(data)/2)
  
  if (num_traces_cur > num_traces) {
    num_traces = num_traces_cur
  }
}

num_cores = params$cores
if (num_traces < num_cores) {
  num_cores = num_traces
}
```

```{r functions, echo=FALSE}
# Functions for reading traces
trace_file = "trace_par"

# Plot all of the traces from a given file
plot_trace_file_data <- function(file) {
  data = read.csv(paste(data_folder, file, sep=""), skip=3)
  plot(data[,1], data[,2], 
       main="Action Potentials",
       ylab="Voltage (mV)",
       xlab="Time (ms)",
       type='l',
       ylim=c(-100,100),
       xlim=c(0,20))
  labs = c(names(data[2]))
  cols = c(rgb(0,0,0))
  for(i in 2:(ncol(data)/2)) {
    cur_col = rgb(0,0,i, max=(ncol(data)/2))
    lines(data[,(2*i-1)], data[,(2*i)], col=cur_col)
    labs = append(labs, names(data[(2*i)]))
    cols = append(cols, cur_col)
  }
  legend(10, 100, 
         legend=labs,
         col=cols,
         lty=1)
}

# Optimize a model to the trace data in a given file
opt_trace_file <- function(file) {
  data = read.csv(paste(data_folder, file, sep=""), skip=3)
  for(i in 1:(ncol(data)/2)) {
    read_trace_data = as.numeric(na.omit(data[,(2*i)]))
    read_time_data = as.numeric(na.omit(data[,(2*(i-1)+1)]))
    AP = ActionPotential(par_0, read_trace_data, read_time_data)
    AP$find_foot()
    AP$optimize()
    AP$display_action_potential()
  }
}

# Optimize a model to the trace data in a given file using 
#   parallelism
opt_trace_file_parallel <- function(file, 
                                    cores=(detectCores() - 1)) {
  data = read.csv(paste(data_folder, file, sep=""), skip=3)
  
  clust = makeCluster(cores)
  clusterExport(clust, c("par_0", "opt_par_0", "data"), 
                envir=environment())
  registerDoParallel(clust)
  fits <- foreach(i = 1:(ncol(data)/2), 
                  .combine = rbind) %dopar% {
    #for(i in 1:(ncol(data)/2)) {
    source("ActionPotential.R")
    
    read_trace_data = as.numeric(na.omit(data[,(2*i)]))
    read_time_data = as.numeric(na.omit(data[,(2*(i-1)+1)]))
    AP = ActionPotential(par_0, read_trace_data, read_time_data, 
                         paste(file, i))
    AP$find_foot()
    #out_par = AP$optimize_split()
    out_par = AP$nudge_optimize(opt_par_0, 25, 1.5)
    #out_par = AP$optimize(opt_par_0)
    
    # Added RMP -- Could be a source of error
    data.frame(t(sapply(out_par$par,c)), values=out_par$value, 
               convergence=out_par$convergence, 
               RMP_val=AP$RMP, dur=AP$stim_d, dim=AP$stim_dim, 
               ht=AP$stim_h, wait=AP$tot_wait)
  }
  stopCluster(clust)
  saveRDS(fits, file = paste(output_folder_trc, file, trace_file,
                             ".Rds", sep=""))
}

# Visualize the optimized trace
show_opt_trace <- function(file) {
  data = read.csv(paste(data_folder, file, sep=""), skip=3)
  fits = readRDS(file = paste(output_folder_trc, file, trace_file,
                              ".Rds", sep=""))
  header_names = c()
  to_csv = data.frame()
  voltage_to_csv = data.frame()
  
  for(i in 1:nrow(fits)) {
    read_trace_data = as.numeric(na.omit(data[,(2*i)]))
    read_time_data = as.numeric(na.omit(data[,(2*(i-1)+1)]))
    AP = ActionPotential(unlist(fits[i,]), read_trace_data, 
                         read_time_data, names(data[2*i]))
    AP$configure_stim(unlist(fits[i,]["dur"]), 
                      unlist(fits[i,]["dim"]), 
                      unlist(fits[i,]["ht"]), 
                      unlist(fits[i,]["wait"]))
    AP$display_action_potential()
    print(names(data[2*i]))
    print(kable(AP$all_params, caption="List of all parameters"))
    
    header_names = append(header_names, names(data[2*i]))
    AP_Vs = AP$Vs
    names(AP_Vs) = seq(0,AP$time,AP$dt)
    
    # Trim down AP_Vs traces with dt=0.005 to dt=0.02
    if (AP$dt == 0.005) {
      AP_Vs = AP_Vs[seq(1, length(AP_Vs), 4)]
    }
    if (i == 1) {
      to_csv = as.data.frame(AP$all_params)
      voltage_to_csv = as.data.frame(AP_Vs)
    } else {
      to_csv = cbind(to_csv, as.data.frame(AP$all_params))
      voltage_to_csv = cbind(voltage_to_csv, as.data.frame(AP_Vs))
    }
  }
  
  means = c()
  sds = c()
  medians = c()
  for(i in 1:ncol(fits)){
    means = append(means, mean(fits[,i]))
    sds = append(sds, sd(fits[,i]))
    medians = append(medians, median(fits[,i]))
  }
  mean_df = data.frame(names(fits), means)
  sd_df = data.frame(names(fits), sds)
  median_df = data.frame(names(fits), medians)
  print(kable(mean_df, caption="Means of Parameters"))
  print(kable(median_df, caption="Medians of Parameters"))
  print(kable(sd_df,caption="Standard Deviations of Parameters"))
  
  names(to_csv) = header_names
  names(voltage_to_csv) = header_names
  to_csv = cbind(to_csv, means)
  to_csv = cbind(to_csv, medians)
  to_csv = cbind(to_csv, sds)
  
  write.csv(to_csv, paste(output_folder_trc, file, trace_file, 
                          "_parameters.csv", sep=""), 
            row.names=TRUE)
  write.csv(voltage_to_csv, 
            paste(output_folder_trc, file, 
                  trace_file, "_voltages.csv", sep=""), 
            row.names=TRUE)
}
```

```{r opt, echo=FALSE}
if(params$run) {
  for(file in trace_files) {
    opt_trace_file_parallel(file,cores=num_cores)
  }
}
```


# Optimizing and Visualization of Individual Traces

```{r main, results="asis", message=FALSE}
print("Optomized paramters")
print(opt_par_0)
for(file in trace_files) {
    plot_trace_file_data(file)
    show_opt_trace(file)
}
```
